version: '3.9'

secrets:
  pgpass:
    file: ./pgpass

services:

  postgres-init:
    image: postgres:17
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "./volumes/postgres/data:/var/lib/postgresql/data"
      - "./pg-init.sh:/docker-entrypoint-initdb.d/pg-init.sh:ro"
    entrypoint: [ "/bin/bash", "./docker-entrypoint-initdb.d/pg-init.sh" ]

  postgres:
    image: lovelysystems/docker-postgres:dev
    depends_on:
      postgres-init:
        condition: service_completed_successfully
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      # bind mount the data volume
      - "./volumes/postgres/data:/var/lib/postgresql/data"

    # configure shared library preload for the debugger extension
      - "./init-cloudnative.sh:/init-cloudnative.sh:ro"
    entrypoint: ["bash", "/init-cloudnative.sh"]

  # pgadmin listening on http://localhost:1080
  pgadmin:
    image: dpage/pgadmin4:6.3
    depends_on:
      - postgres
    secrets:
      # the pass file to use with the pre configured server
      - source: pgpass
        mode: 600
        target: /var/lib/pgadmin/storage/admin/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      # local storage for pgadmin
      - ./volumes/pgadmin/data:/var/lib/pgadmin
      # the server definition file, only read on first start
      - ./servers.json:/pgadmin4/servers.json:ro
    ports:
      - "1080:80"

  client:
    image: lovelysystems/docker-postgres:dev-client
    profiles:
      - manual
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
