version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run:
          name: Bootstrap Gradle
          command: ./gradlew --version
      - run:
          name: Prepare docker container builder
          # ignore failures since builder could exist already (cache)
          command: ./gradlew prepareDockerContainerBuilder || true
      - run:
          name: Check
          command: ./gradlew check
workflows:
  test:
    jobs:
      - test
