#!/bin/bash
set -e
# based on https://github.com/tianon/docker-postgres-upgrade/blob/master/12-to-16/docker-upgrade


if [ "$#" -eq 0 -o "${1:0:1}" = '-' ]; then
	set -- pg_upgrade "$@"
fi

if [ "$1" = 'pg_upgrade' -a "$(id -u)" = '0' ]; then
    old_owner=$(stat -c '%U' "$PGDATAOLD")
    if [ "$old_owner" != "postgres" ]; then
      echo "owner of old data directors is not postgres it is $old_owner"
      exit 1
    fi
	  chmod 700 "$PGDATANEW"
	  chown -R postgres "$PGDATANEW"
  	exec gosu postgres "$BASH_SOURCE" "$@"
fi

if [ "$1" = 'pg_upgrade' ]; then
    echo in second

	if [ ! -s "$PGDATANEW/PG_VERSION" ]; then
		PGDATA="$PGDATANEW" eval "initdb $POSTGRES_INITDB_ARGS"
	fi
	echo "copying over pg_hba.conf"
	cp -p $PGDATAOLD/pg_hba.conf $PGDATANEW/pg_hba.conf
fi

exec "$@"
