version: '3.9'

services:

  pg12:
    image: lovelysystems/docker-postgres:12.9.0
    stop_grace_period: 120s
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./data/12:/var/lib/postgresql/data"
      - "./fill_db.sh:/docker-entrypoint-initdb.d/fill_db.sh:ro"

  client:
    image: lovelysystems/docker-postgres:dev-client
    profiles:
      - manual
    environment:
      PGHOST: pg12
      PGUSER: postgres
      PGPASSWORD: postgres

  upgrade:
    image: lovelysystems/docker-postgres:dev-upgrade12
    stop_grace_period: 120s
    profiles:
      - manual
    volumes:
      - "./data/12:/var/lib/postgresql/12/data"
      - "./data/14:/var/lib/postgresql/14/data"

  pg14:
    image: lovelysystems/docker-postgres:dev
    stop_grace_period: 120s
    profiles:
      - manual
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./data/14:/var/lib/postgresql/data"


